### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by liamxg** [PoonLab/clustuneR#16]
<img width="1064" alt="image" src="https://github.com/PoonLab/clustuneR/assets/46078579/950a9f51-be13-4ecb-833d-432ab983d24a">

**Comment by ArtPoon** [comment]
Sorry for the delayed response.  What OS and version of R are you using?

**Comment by ArtPoon** [comment]
The `guppy` and `pplacer` binaries that we are distributing in the `inst` directory of this package are compiled for Linux platforms only.  They will not run in macOS or Windows.

**Comment by ArtPoon** [comment]
Based on your screenshot it looks like you are running macOS.  I am attempting to compile pplacer binaries for macOS but it is not a trivial process.  Presently I am stuck at this point of the build (copying command history here for record):
```console
art@Wernstrom pplacer-1.1.alpha19 % brew install opam
art@Wernstrom pplacer-1.1.alpha19 % brew search camlp4-extra
==> Formulae
camlp-streams
art@Wernstrom pplacer-1.1.alpha19 % brew install camlp-streams
art@Wernstrom pplacer-1.1.alpha19 % brew install gawk
art@Wernstrom pplacer-1.1.alpha19 % brew install zlib
art@Wernstrom git % git clone https://github.com/matsen/pplacer.git
art@Wernstrom pplacer % brew install curl
art@Wernstrom pplacer % command -v ocamlc && ( ocamlc -version | grep -q 3.12.1 ) || opam switch install 3.12.1
/usr/local/bin/ocamlc

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><>  🐫 
Switch invariant: ["ocaml-base-compiler" {= "3.12.1"} | "ocaml-system" {= "3.12.1"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] Failed to get sources of ocaml-base-compiler.3.12.1: Download command failed

#=== ERROR while fetching sources for ocaml-base-compiler.3.12.1 ==============#
OpamSolution.Fetch_fail("http://caml.inria.fr/pub/distrib/ocaml-3.12/ocaml-3.12.1.tar.gz (Download command failed: \"/usr/local/bin/wget --content-disposition -t 3 -O /Users/art/.opam/3.12.1/.opam-switch/sources/ocaml-base-compiler.3.12.1/ocaml-3.12.1.tar.gz.part -U opam/2.1.5 -- http://caml.inria.fr/pub/distrib/ocaml-3.12/ocaml-3.12.1.tar.gz\" exited with code 256)")
```

**Comment by ArtPoon** [comment]
Found a solution in a similar [GitHub issue](https://github.com/orgs/Homebrew/discussions/4819).
This got me past the Download failure, but now stuck at another error:
```console
art@Wernstrom pplacer % brew upgrade libidn2
art@Wernstrom pplacer % command -v ocamlc && ( ocamlc -version | grep -q 3.12.1 ) || opam switch install 3.12.1
⬇ retrieved ocaml-base-compiler.3.12.1  (http://caml.inria.fr/pub/distrib/ocaml-3.12/ocaml-3.12.1.tar.gz)
[ERROR] The compilation of ocaml-base-compiler.3.12.1 failed at "make world.opt".

#=== ERROR while compiling ocaml-base-compiler.3.12.1 =========================#
# context     2.1.5 | macos/x86_64 |  | git+https://github.com/ocaml/opam-repository.git
# path        ~/.opam/3.12.1/.opam-switch/build/ocaml-base-compiler.3.12.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make world.opt
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-12371-c67484.env
# output-file ~/.opam/log/ocaml-base-compiler-12371-c67484.out
### output ###
# [...]
# make[2]: Nothing to be done for `all'.
# /Library/Developer/CommandLineTools/usr/bin/make runtimeopt
# cd asmrun; /Library/Developer/CommandLineTools/usr/bin/make all
# cc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_macosx  -O -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o startup.o startup.c
# startup.c:162:3: error: call to undeclared function 'caml_debugger_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
#   caml_debugger_init (); /* force debugger.o stub to be linked */
#   ^
# 1 error generated.
# make[3]: *** [startup.o] Error 1
# make[2]: *** [makeruntimeopt] Error 2
# make[1]: *** [opt-core] Error 2
# make: *** [world.opt] Error 2
```

**Comment by ArtPoon** [comment]
Looks like `cc` calls clang on macOS Ventura (13.5.2)
```console
art@Wernstrom pplacer % cc
clang: error: no input files
```

There's also a macOS (Darwin) binary of an older release of pplacer.  It requires an older version of libgsl then what is installed by my current version of Homebrew, however:
```console
(venv) art@Wernstrom pplacer-Darwin-v1.1.alpha17-6-g5cecf99 % ./pplacer       
dyld[18808]: Library not loaded: /usr/local/lib/libgsl.0.dylib
  Referenced from: <0D61E9B0-4DB5-3D60-99A8-F091685CDB35> /Users/art/Downloads/pplacer-Darwin-v1.1.alpha17-6-g5cecf99/pplacer
  Reason: tried: '/usr/local/lib/libgsl.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libgsl.0.dylib' (no such file), '/usr/local/lib/libgsl.0.dylib' (no such file), '/usr/lib/libgsl.0.dylib' (no such file, not in dyld cache)
zsh: abort      ./pplacer
(venv) art@Wernstrom pplacer-Darwin-v1.1.alpha17-6-g5cecf99 % brew info gsl  
==> gsl: stable 2.7.1 (bottled)
Numerical library for C and C++
```
This is a known issue: https://groups.google.com/g/pplacer-users/c/FhJyH9MUY78

I'll try compiling an older version of libgsl (version 1.16) and see if this pplacer binary can locate the resulting dynamic libraries.

**Comment by ArtPoon** [comment]
Ok, I was able to run the Darwin binaries for pplacer release [v1.1.alpha17](https://github.com/matsen/pplacer/releases/tag/v1.1.alpha17) after installing an older version of libgsl.
Steps:
1. Download a copy of the GSL library (version 1.16) from: https://mirror2.evolution-host.com/gnu/gsl/
2. Uncompress the archive with `tar -xvzf gsl-1.16.tar.gz`
3. Enter this directory (`cd gsl-1.16`) and run `./configure`
4. Run `make` and then `sudo make install`.  If you do not have superuser privileges on your system, then you will have to install the library files somewhere that `pplacer` is going to find them.  This will probably mean modifying your `$DYLD_LIBRARY_PATH` environment variable (see https://discussions.apple.com/thread/1670523 for a related example).
5. You should now be able to run the pplacer `Darwin` binary by calling its relative or absolute path:
```console
art@Wernstrom pplacer-Darwin-v1.1.alpha17-6-g5cecf99 % ls
guppy	pplacer	rppr	scripts
art@Wernstrom pplacer-Darwin-v1.1.alpha17-6-g5cecf99 % ./pplacer
Warning: pplacer couldn't find any sequences to place. Please supply an alignment with sequences to place as an argument at the end of the command line.
```
Finally, you'll need to move these binaries to replace the Linux binaries in the `inst` folder of the `clustuneR` package distribution.

**Comment by ArtPoon** [comment]
Looks like you are still in the `gsl` directory.  You need to be in the `pplacer` directory.

**Comment by ArtPoon** [comment]
* Direct your browser to https://github.com/matsen/pplacer/releases/tag/v1.1.alpha17
* Click on the link to the asset *pplacer-Darwin-v1.1.alpha17.zip*.  If you do not see this link, you may have to open the Assets tab by clicking on that label.  You should then see something like this:
  <img width="250" alt="Screenshot 2023-11-12 at 11 34 19 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/103d5927-e5bb-4561-a2cc-f77c60d4f6cf">

* This will cause your browser to download a ZIP archive, probably to the Downloads folder on your Mac.  Go to your Downloads folder and double-click on the archive file (`pplacer-Darwin-v1.1.alpha17.zip`) to uncompress it.
* You will now find a folder labelled `pplacer-Darwin-v1.1.alpha17-6-g5cecf99` within your Downloads folder:
  <img width="400" alt="Screenshot 2023-11-12 at 11 37 08 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/6a0d3ead-e952-439a-a998-132f0cb42d32">

* Move the files `pplacer` and `guppy` to the folder `inst` within the clustuneR folder:
  <img width="350" alt="Screenshot 2023-11-12 at 11 38 30 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/5c9eb1b6-d78e-4ec9-80cf-3ea02214d51d">

  It is fine to overwrite the files that are already there - they are Linux binaries and will not run on your macOS computer.

* Open your [Terminal app](https://support.apple.com/en-ca/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac) and change directories to this `inst` folder with `cd` commands.
* Attempt to run the pplacer binary with the command `./pplacer`.  Your system will block this program from running:
  <img width="300" alt="Screenshot 2023-11-12 at 11 41 28 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/8956c32a-96d5-4e70-af7c-047fb86da258">

  Dismiss this pop-up by clicking on the Cancel button.
* Open your [System Settings](https://en.wikipedia.org/wiki/System_Settings) application and go to the Privacy & Security panel.  You should see something like this:
  <img width="500" alt="Screenshot 2023-11-12 at 11 44 27 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/534f490e-ea90-4999-ac2a-111aabfc3573">

* Click on the "Allow Anyway" button, because we're going to trust the binaries distributed from the Matsen group.
* Go back to Terminal and run the `./pplacer` command again.  This will cause another pop-up to appear:
<img width="250" alt="Screenshot 2023-11-12 at 11 45 38 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/3653d743-60fc-4758-a411-2c0cc83d705d">

* Click on the "Open" button.  Your terminal should now display something like the following:
  <img width="600" alt="Screenshot 2023-11-12 at 11 46 54 AM" src="https://github.com/PoonLab/clustuneR/assets/1109328/db55a5ef-547b-4fc4-87f0-50bdb617a8ba">

  This means that the `pplacer` binary is running normally.

**Comment by ArtPoon** [comment]
You'll need to go through the same process to enable the `guppy` binary.

**Comment by ArtPoon** [comment]
Those are the expected outputs.  Your binaries are working.

**Comment by ArtPoon** [comment]
You need to rerun the command `R CMD INSTALL .` to copy these new binaries into your system R directory.
